title:              개발노트
email:              joyoungjae0401@gmail.com
description:        되새기는 개발노트
author:             ""
baseurl:            ""
url:                "https://youngjae0401.github.io/develop_note/"

# Social Profiles
twitter_username:   
github_username:    youngjae0401
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-W4BPWTW6MH # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           20
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
